alerts:
  print-to-console: true
  proxy:
    send: false
    receive: false

verbose:
  print-to-console: false

client-brand:
  ignored-clients:

spectators:
  hide-regardless: false
  allowed-worlds:
    - ""

max-transaction-time: 60

Simulation:
  setback-decay-multiplier: 0.000
  threshold: 0.050
  immediate-setback-threshold: -1
  max-advantage: -1
  max-ceiling: 4

Phase:
  setbackvl: 64
  decay: 0.050

AirLiquidPlace:
  cancelvl: 64

FabricatedPlace:
  cancelvl: 64

FarPlace:
  cancelvl: 64

PositionPlace:
  cancelvl: 64

RotationPlace:
  cancelvl: 64

NoSlow:
  threshold: 0.125
  setbackvl: 64
  decay: 0.05

Knockback:
  threshold: 0.125
  setbackvl: 64

Explosion:
  threshold: 0.125
  setbackvl: 64

TimerA:
  setbackvl: 64
  drift: 120

NegativeTimer:
  drift: 1200

TimerVehicle:
  setbackvl: 64

EntityControl:
  setbackvl: 64

Reach:
  threshold: 0.04
  block-impossible-hits: false
  enable-post-packet: false

debug-pipeline-on-join: false

experimental-checks: false

packet-spam-threshold: 100

config-version: 8
